"""Generate the Lane C declarative study spec from a vendored config.

Lane C demonstrates the SDK *study layer* driving the registered ``evt`` runner:
one study spec, expanded into many cases, each a workflow script over the evt
tool registry. The range axis is the one genuinely scalar axis in the paper's
matrix (range is encoded purely in ``mission.cruise_s``), so it expresses
cleanly as a study.

This emits ``range_study.yaml`` for Archer Midnight at 1500 ft, sweeping the
three mission ranges (30/45/60 mi -> cruise_s 558/918/1278 s). The base config
is read from the vendored ``cfg/archer-midnight-1500-30.json`` so the YAML never
drifts from the case inputs; re-run this script to regenerate after a pin bump.

The altitude axis touches ~10 coupled keys (air density, viscosity, segment
durations), so it is a data-driven axis rather than a scalar sweep; Lanes A and
B carry the full 2-altitude x 3-vehicle x 3-range grid from the 18 configs.

    uv run python packages/evt/examples/abu_scitech_2026/lane_c/gen_study.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

_LANE_C = Path(__file__).resolve().parent
_EXAMPLE_ROOT = _LANE_C.parent
sys.path.insert(0, str(_EXAMPLE_ROOT))
from shared import RANGES_MI, config_path  # noqa: E402

# Range (mi) -> cruise_s (s) for Archer Midnight at 1500 ft, read from the
# vendored configs so the axis matches the inputs exactly.
_BASE = json.loads(config_path("archer-midnight", 1500, 30).read_text())


def _cruise_s(range_mi: int) -> float:
    return float(json.loads(config_path("archer-midnight", 1500, range_mi).read_text())
                 ["mission"]["cruise_s"])


def build_study() -> dict:
    steps = [
        {"id": "vehicle", "tool": "define_vehicle",
         "args": {"params": _BASE["aircraft"]}},
        {"id": "propulsion", "tool": "set_propulsion",
         "args": {"params": _BASE["propulsion"]}},
        {"id": "power", "tool": "set_power", "args": {"params": _BASE["power"]}},
        {"id": "environ", "tool": "set_environment",
         "args": {"params": _BASE["environ"]}},
        {"id": "cfg_mission", "tool": "configure_mission",
         "args": {"params": _BASE["mission"]}},
        {"id": "mission", "tool": "run_mission_analysis", "args": {}},
        {"id": "size", "tool": "run_sizing", "args": {}},
    ]

    cases = []
    for r in RANGES_MI:
        cases.append({
            "case": {
                "id": f"archer-1500-{r}",
                "params": {"range_mi": r},
                "spec": {
                    "set": {"steps[cfg_mission].args.params.cruise_s": _cruise_s(r)},
                },
            }
        })

    return {
        "metadata": {
            "id": "abu-scitech-2026-archer-1500-range",
            "name": "ABU SciTech 2026 -- Archer Midnight 1500 ft range sweep",
            "version": 1,
            "description": (
                "Lane C declarative study: the evt runner over the range axis "
                "(cruise_s) for Archer Midnight at 1500 ft. Reaches the same "
                "energy and sized-MTOW numbers as Lanes A/B for these three "
                "cells. Altitude and vehicle are data-driven axes carried by "
                "Lanes A/B over the 18 vendored configs."
            ),
        },
        "defaults": {
            "runner": "evt",
            "spec": {"steps": steps, "run_ref_step": "size"},
        },
        "cases": cases,
        "execution": {
            "workers": 1,
            "est_case_seconds": 5,
            "review_threshold": 6,
            "guard_max_cases": 12,
        },
        "outputs": [
            {"name": "sized_mtow_kg", "path": "size:results.sized_mtow_kg"},
            {"name": "total_mission_energy_kw_hr",
             "path": "mission:results.totals.total_mission_energy_kw_hr"},
        ],
    }


def write_study(out_path: Path | None = None) -> Path:
    out_path = out_path or (_LANE_C / "range_study.yaml")
    study = build_study()
    header = (
        "# GENERATED by lane_c/gen_study.py from cfg/archer-midnight-1500-*.json.\n"
        "# Do not edit by hand; re-run the generator to regenerate.\n"
    )
    out_path.write_text(header + yaml.safe_dump(study, sort_keys=False), encoding="utf-8")
    return out_path


if __name__ == "__main__":
    print(f"wrote {write_study()}")
